import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createRouter, RouterInputError } from '../dist/index.js';
import { jsonState, RouterInputError as InternalInputError } from '../tmp/units/units.js';
const make = (more = {}) => createRouter({ baseUrl: 'https://app.test/console/', basePath: '/console/', routes: [
  { id: 'home', path: '/' }, { id: 'person', path: '/people/:id' }, { id: 'version', path: '/api/v:version/endpoints/*' }, { id: 'search', path: '/search' }, { id: 'fallback', path: '*' },
], ...more });
// Internal units come from a separate test bundle, so their errors are instances of its own RouterInputError class.
const code = expected => e => (e instanceof RouterInputError || e instanceof InternalInputError) && e.code === expected;
for (const [input, path, search, hash] of [
  ['?q=next', '/', '?q=next', ''], ['#anchor', '/', '', '#anchor'], ['people/42', '/people/42', '', ''],
  ['https://app.test/console/people/42?a=1#a', '/people/42', '?a=1', '#a'], ['../console/search', '/search', '', ''],
]) test(`resolve ${input}`, () => { const r = make(); const q = r.resolve(input); assert.equal(q.path, path); assert.equal(q.search, search); assert.equal(q.hash, hash); assert.equal(new URL(q.href).pathname, q.pathname); });
test('pure destination request and no current-state mutation', () => { const r = make(); const s = r.getSnapshot(); const a = r.resolve('/console/people/9?q=x#y'); assert.equal(a.routeId, 'person'); assert.equal(a.params.id, '9'); assert.equal(a.search, '?q=x'); assert.equal(r.getSnapshot(), s); });
test('duplicate query entries retain order; raw search is not reserialized', () => { const q = make().resolve('search?q=a%20b&q=two&x=+'); assert.deepEqual(q.query, [['q','a b'],['q','two'],['x',' ']]); assert.equal(q.search, '?q=a%20b&q=two&x=+'); });
test('fragments are anchors, not dictionaries', () => assert.equal(make().resolve('#section-2').hash, '#section-2'));
test('decode parameters exactly once after structural matching', () => { const r = make(); assert.equal(r.resolve('people/a%2Fb').params.id, 'a/b'); assert.equal(r.resolve('people/a%252Fb').params.id, 'a%2Fb'); });
test('full dynamic pattern matching with optional trailing slash', () => { assert.equal(make().resolve('people/42/').routeId,'person'); });
test('embedded parameter and wildcard', () => { const q = make().resolve('api/v2/endpoints/users/3'); assert.equal(q.params.version,'2'); assert.equal(q.params.wildcard,'users/3'); });
test('literal regex punctuation is escaped', () => { const r = make({ routes: [{id:'literal',path:'/v1.0/(a)+[b]$'}] }); assert.equal(r.resolve('/console/v1.0/(a)+[b]$').match,true); assert.equal(r.resolve('/console/v1x0/aaab').match,false); });
test('registration order is explicit', () => { const r=make({routes:[{id:'param',path:'/people/:id'},{id:'new',path:'/people/new'}]}); assert.equal(r.resolve('people/new').routeId,'param'); });
test('unmatched still contains destination URL', () => { const r=make({routes:[]}); const q=r.resolve('unknown?q=1#h'); assert.equal(q.match,false); assert.equal(q.routeId,null); assert.equal(q.path,'/unknown'); assert.equal(q.search,'?q=1'); });
test('dangerous dictionary keys are data', () => { const r=make({routes:[{id:'data',path:'/:__proto__/:constructor'}]}); const q=r.resolve('/console/one/two?__proto__=three'); assert.equal(q.params.__proto__,'one'); assert.equal(q.params.constructor,'two'); assert.equal(Object.getPrototypeOf(q.params),null); });
for (const [href, error] of [['https://else.test/a','outside-origin'], ['/other','outside-base'], ['/console-other/a','outside-base'], ['javascript:alert(1)','invalid-url'], ['https://u:p@app.test/console/','invalid-url'], ['people/%zz','invalid-encoding'], ['people/%C0%AF','invalid-encoding'], ['people/ok?q=%FF','invalid-encoding'], ['people/ok#%','invalid-encoding'], ['a\\b','invalid-url'], ['a\nb','invalid-url']])
  test(`reject ${error}: ${JSON.stringify(href)}`, () => assert.throws(()=>make().resolve(href),code(error)));
test('base-root and base-prefix semantics', () => { const r=make(); assert.equal(r.resolve('/console').path,'/'); assert.throws(()=>r.resolve('/people/42'),code('outside-base')); assert.equal(r.href({id:'person',params:{id:'42'}}),'/console/people/42'); });
test('named builder preserves data, duplicate query, anchor', () => { const r=make(); const href=r.href({id:'person',params:{id:'ä / ? # %'},query:[['q','a'],['q','b']],hash:'hello #world'}); const q=r.resolve(href); assert.equal(q.params.id,'ä / ? # %'); assert.deepEqual(q.query,[['q','a'],['q','b']]); assert.equal(decodeURIComponent(q.hash.slice(1)),'hello #world'); });
test('wildcard builder preserves segment boundaries', () => { const r=make(); const h=r.href({id:'version',params:{version:'2',wildcard:'a b/c'}}); assert.equal(h,'/console/api/v2/endpoints/a%20b/c'); });
test('builders reject missing extra and dot parameters', () => { const r=make(); for (const params of [{},{id:'.'},{id:'..'},{id:'x',other:'y'}]) assert.throws(()=>r.href({id:'person',params}),code('invalid-route')); assert.throws(()=>r.href({id:'bad'}),code('invalid-route')); });
for (const routes of [ [{id:'x',path:'/x'},{id:'x',path:'/y'}], [{id:'x',path:'/x'},{id:'y',path:'/x/'}], [{id:'x',path:'/:a/:a'}], [{id:'x',path:'/x*'}], [{id:'x',path:'/x/*/y'}], [{id:'x',path:'/:wildcard/*'}], [{id:'x',path:'/x?y'}], [{id:'x',path:'//outside'}], [{id:'x',path:'/x\ty'}], [{id:'x',path:'/x\u0000y'}]])
  test(`reject ambiguous pattern ${JSON.stringify(routes)}`, () => assert.throws(()=>make({routes}),code('invalid-route')));
test('hash shell and logical request are distinct', () => { const r=make({mode:'hash',baseUrl:'https://app.test/console/index.html?outer=1'}); const q=r.resolve('#/people/42?q=x#section'); assert.equal(q.pathname,'/console/index.html'); assert.equal(q.path,'/people/42'); assert.equal(q.search,'?q=x'); assert.equal(q.hash,'#section'); assert.equal(r.href({id:'person',params:{id:'42'},query:[['a','1']],hash:'x'}),'/console/index.html?outer=1#/people/42?a=1#x'); assert.equal(r.resolve('').path,'/'); });
test('hash mode rejects physical query/path/anchor confusion', () => { const r=make({mode:'hash',baseUrl:'https://app.test/console/index.html?outer=1'}); for (const h of ['?logical=wrong','other.html#/','/console/other#/','#anchor','#//evil.test/']) assert.throws(()=>r.resolve(h),code('outside-shell')); });
test('immutable requests snapshots and state', () => { const r=make(); const q=r.resolve('people/42?q=a'); for(const f of [()=>q.params.id='bad',()=>q.query.push(['x','y']),()=>q.path='/bad',()=>r.getSnapshot().state=42]) assert.throws(f,TypeError); const original={b:[1,2],a:1}; const state=jsonState(original); original.b.push(3); assert.equal(JSON.stringify(state),'\u007b"a":1,"b":[1,2]}'); });
// oxlint-disable-next-line no-sparse-arrays -- sparse arrays are deliberately invalid input
test('JSON state rejects host objects cycles nonfinite numbers accessors and sparse arrays', () => { const cyclic={};cyclic.x=cyclic; for(const v of [cyclic,new Date(),Infinity,NaN,undefined,()=>{},[,,],{get x(){throw Error('must not execute')}},{[Symbol()]:1}]) assert.throws(()=>jsonState(v),code('invalid-state')); });
test('JSON state is insertion-order independent with safe property names', () => { assert.equal(JSON.stringify(jsonState({z:1,a:2})),JSON.stringify(jsonState({a:2,z:1}))); const q=jsonState(JSON.parse('{"__proto__":"a"}')); assert.equal(q.__proto__,'a'); });
test('instance registrations isolated', () => { const a=make({routes:[{id:'a',path:'/a'}]}),b=make({routes:[{id:'b',path:'/b'}]}); assert.equal(a.resolve('b').match,false);assert.equal(b.resolve('b').match,true); });
test('not-started and destroyed settle, ready before start is resolved by destruction', async () => { const r=make(); assert.equal((await r.navigate('/console/')).status,'rejected'); const ready=r.ready(); await r.destroy(); assert.equal((await ready).error.code,'destroyed'); assert.equal((await r.navigate('/console/')).error.code,'destroyed'); await r.destroy(); });
test('callbacks can change but structure cannot', () => { const r=make(); r.config({prepare:()=>({commit(){}})}); assert.throws(()=>r.config({basePath:'/new'}),code('invalid-route')); });

test('Unicode static patterns match URL-standard encoded paths',()=>{ const r=make({routes:[{id:'cafe',path:'/café/:id'}]});assert.equal(r.resolve('café/42').routeId,'cafe');assert.equal(r.href({id:'cafe',params:{id:'ä'}}),'/console/caf%C3%A9/%C3%A4'); });
// oxlint-disable-next-line no-sparse-arrays -- sparse arrays are deliberately invalid input
test('invalid builder dictionaries and sparse query pairs fail with typed input errors',()=>{const r=make();assert.throws(()=>r.href({id:'person',params:null}),code('invalid-route'));assert.throws(()=>r.href({id:'home',query:[[,,]]}),code('invalid-url'));});
test('dot-segment patterns are rejected, not silently rewritten',()=>{for(const path of ['/x/../y','/x/%2e/y'])assert.throws(()=>make({routes:[{id:'x',path}]}),code('invalid-route'));});
test('subscriptions and guards cannot be added after destruction',async()=>{const r=make();await r.destroy();assert.throws(()=>r.subscribe(()=>{}),code('destroyed'));assert.throws(()=>r.beforeEach(()=>true),code('destroyed'));});

 test('cross-realm plain JSON state is accepted, host prototypes are not',async()=>{const {runInNewContext}=await import('node:vm');assert.equal(JSON.stringify(jsonState(runInNewContext('({x:[1,2]})'))),'{"x":[1,2]}');assert.throws(()=>jsonState(runInNewContext('new Date()')),code('invalid-state'));});
 test('structural options are snapshotted rather than retained mutably',()=>{const config={baseUrl:'https://one.test/',routes:[{id:'home',path:'/'}]};const r=createRouter(config);config.baseUrl='https://other.test/';config.routes.push({id:'a',path:'/a'});assert.equal(r.resolve('/').origin,'https://one.test');assert.equal(r.resolve('/a').match,false);});
